# Generated by Django 4.1.1 on 2022-11-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre1', models.CharField(max_length=200)),
                ('preparación1', models.TextField(max_length=5000)),
                ('foto1', models.FileField(upload_to='media/fotos')),
            ],
        ),
    ]
