# Generated by Django 4.1.1 on 2022-11-28 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_prueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
